name: CI CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd apps/crispChat
            git pull origin main
            npm install
            pm2 restart crispchat
            